FROM apache/airflow:3.3.2

USER root

RUN apt-get update \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

USER airflow

RUN pip install --no-cache-dir \
    duckdb \
    pandas \
    dbt-core \
    dbt-duckdb